<?php
namespace NiroRoadmap\Controller\Common;

defined( 'ABSPATH' ) || exit;

class Blocks {
	/**
	 * Constructor to add all blocks.
	 */
	public function __construct() {
		add_action( 'init', [ $this, 'niroroadmap_blocks_init' ] );
	}

	public function niroroadmap_blocks_init() {
		$manifest = NIROROADMAP_PLUGIN_DIR . 'build/blocks-manifest.php';

		/**
		 * Bail if the blocks have not been built yet. The `build` directory is
		 * generated by `npm run build:blocks` and is not tracked in the repo, so
		 * it is absent in a fresh checkout. Without this guard WordPress 6.7
		 * notices the missing manifest and 6.0-6.6 fatals on the require below.
		 */
		if ( ! file_exists( $manifest ) ) {
			return;
		}

		/**
		 * Registers the block(s) metadata from the `blocks-manifest.php` and registers the block type(s)
		 * based on the registered block metadata.
		 * Added in WordPress 6.8 to simplify the block metadata registration process added in WordPress 6.7.
		 *
		 * @see https://make.wordpress.org/core/2025/03/13/more-efficient-block-type-registration-in-6-8/
		 */
		if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
			wp_register_block_types_from_metadata_collection( NIROROADMAP_PLUGIN_DIR . 'build', $manifest );
			return;
		}

		/**
		 * Registers the block(s) metadata from the `blocks-manifest.php` file.
		 * Added to WordPress 6.7 to improve the performance of block type registration.
		 *
		 * @see https://make.wordpress.org/core/2024/10/17/new-block-type-registration-apis-to-improve-performance-in-wordpress-6-7/
		 */
		if ( function_exists( 'wp_register_block_metadata_collection' ) ) {
			wp_register_block_metadata_collection( NIROROADMAP_PLUGIN_DIR . 'build', $manifest );
		}
		/**
		 * Registers the block type(s) in the `blocks-manifest.php` file.
		 *
		 * @see https://developer.wordpress.org/reference/functions/register_block_type/
		 */
		$manifest_data = require $manifest;
		foreach ( array_keys( $manifest_data ) as $block_type ) {
			register_block_type( NIROROADMAP_PLUGIN_DIR . "build/{$block_type}" );
		}
	}
}
